### ISSUE TITLE
Imports duplicados

### ISSUE THREAD

**Issue by franklevel** [gabyreload1983/coderHouseBackend-GabrielGodoy#3]
https://github.com/gabyreload1983/coderHouseBackend-GabrielGodoy/blob/58946c8eeef8cb0e7bb19187a1f870bfdaeed353/src/utils.js#L2

En la línea de arriba puedes importar el path y así te ahorras agregar la linea de mas abajo.

Quedaria asi: 
`import path, { dirname } from "path"; `

**Comment by gabyreload1983** [comment]
Listo, aplique la correccion. Muchas gracias por la observacion.
